  - name: Flyway Migration
  # You may pin to the exact commit or the version.
  # uses: joshuaavalon/flyway-action@81e2f01520d51d5fb5cb2ef828229adc5820aa2d
  uses: joshuaavalon/flyway-action@v3.0.0
  with:
    # The jdbc url to use to connect to the database
    url: 
    # The user to use to connect to the database
    user: # optional
    # The password to use to connect to the database
    password: # optional
    # Comma-separated list of locations to scan recursively for migrations
    locations: # default is filesystem:./sql
    # The SQL statements to run to initialize a new database connection immediately after opening it
    initSql: # optional
